<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.1">
    <title>Links for odoo13-addon-product-exception</title>
  </head>
  <body>
    <h1>Links for odoo13-addon-product-exception</h1>
    <a href="https://files.pythonhosted.org/packages/ff/8e/f162629131e5fa771a0985b4d8e0590614ca370dcb2df9ba982d678f7dd3/odoo13_addon_product_exception-13.0.1.0.1-py3-none-any.whl#sha256=277130e9334c1aea3461a22d90a4c3141b88c136974017467ea18744ff894dca" data-requires-python="&gt;=3.5" data-dist-info-metadata="sha256=725279ea35cf2b6cf61384106ef4d66a543ae598351f26445799c29ae25c6c54" data-core-metadata="sha256=725279ea35cf2b6cf61384106ef4d66a543ae598351f26445799c29ae25c6c54">odoo13_addon_product_exception-13.0.1.0.1-py3-none-any.whl</a><br />
    </body>
</html>
<!--SERIAL 18560500-->