<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.1">
    <title>Links for odoo13-addon-partner-exception</title>
  </head>
  <body>
    <h1>Links for odoo13-addon-partner-exception</h1>
    <a href="https://files.pythonhosted.org/packages/5b/43/4277880712831fb12b9ea4c7fb929dbb079e92c4a0a3b02569fefbae21a8/odoo13_addon_partner_exception-13.0.1.0.1.dev2-py3-none-any.whl#sha256=6cd50c07e62a20fccf2efe23e4cd3a12f9a09182fea5be4bd8368ad38f21a68c" data-requires-python="&gt;=3.5" >odoo13_addon_partner_exception-13.0.1.0.1.dev2-py3-none-any.whl</a><br />
    </body>
</html>
<!--SERIAL 17132563-->