<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.1">
    <title>Links for odoo14-addon-account-move-exception</title>
  </head>
  <body>
    <h1>Links for odoo14-addon-account-move-exception</h1>
    <a href="https://files.pythonhosted.org/packages/30/84/94f5138a1cbefa80b6fa1ab61dc97f8a4868eb0e7e974ece385025057420/odoo14_addon_account_move_exception-14.0.1.0.1.dev3-py3-none-any.whl#sha256=02baa77c4c81ccd0e430ecac03300abd267a7d60a54cc3d071860eda4b491d2c" data-requires-python="&gt;=3.6" >odoo14_addon_account_move_exception-14.0.1.0.1.dev3-py3-none-any.whl</a><br />
    <a href="https://files.pythonhosted.org/packages/5b/7a/d8b5ce230ba1d1637d0d4a2f18951d4d3c3429abae804b72da32a0390abb/odoo14_addon_account_move_exception-14.0.1.0.1.dev5-py3-none-any.whl#sha256=e9f596247d55f954381096bb3931f3b2c91474b1a98a64c73068d4373a512661" data-requires-python="&gt;=3.6" >odoo14_addon_account_move_exception-14.0.1.0.1.dev5-py3-none-any.whl</a><br />
    </body>
</html>
<!--SERIAL 12793805-->